### ISSUE TITLE
Websocket connection to Exasolo

### ISSUE THREAD

**Issue by abergmeier** [EXASOL/websocket-api#10]
When I actually try the sample against an Exasolo (`with EXASOL.connect('ws://192.168.56.2:8563', 'sys', 'exasol') as connection:`), I get:

`websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.`

Similar behavior, if I try to connect with Scala. Is it possible to test the Websocket API with Exasolo at all?

**Comment by wildraid** [comment]
Can you connect with ODBC or JDBC driver using this IP address? Maybe your IP address is different (10.10.xx.xx something).

You may check it in ExaOperation, column connection string.

**Comment by abergmeier** [comment]
Does not matter currently - use a standard database for now.
Would be great to be able to test against an Exasol with Kubernetes, though.

**Comment by wildraid** [comment]
Websocket API works with Kubernetes, Docker, etc.
I know few people using this setup in production. :)
