### ISSUE TITLE
Password field in console.html has input type="text".

### ISSUE THREAD

**Issue by awakenine** [exasol/websocket-api#12]
https://github.com/exasol/websocket-api/blob/26ce3ef183be95cfff08fefe2dd42fadb13d0621/javascript/console.html#L401

There are two rather different security issues involved.

One of them is the one so often mentioned as a reason for using input type=password: to protect the user against prying eyes. This is seldom relevant, since passwords are normally typed (and should be typed) so that there is nobody else looking at your screen or your hands.

The other one is different treatment of input type=text and input type=password by browsers in their histories and in using previously entered data as defaults or as selectable options. This varies by browser, but quite often, input type=text causes an automatic prefill if data has previously been entered in a field with the same name. Using the autocomplete=off attribute usually prevents this in modern browsers. On the other hand, browsers may store username/password pairs to make frequent visits to a site more comfortable; this can be an essential usability improvement and an essential security threat. It is typically based on recognizing a pair of input type=text and input type=password.

**Comment by exazg** [comment]
This issue has been fixed in pull request #26. Thanks for reporting the issue!
