### ISSUE TITLE
Python: KeyError in executemany if the query doesn't contain parameters

### ISSUE THREAD

**Issue by tkilias** [exasol/websocket-api#15]
```
import EXASOL
  
with EXASOL.connect('ws://127.0.0.1:8888', 'sys', 'exasol') as connection:
     with connection.cursor() as cursor:
          cursor.executemany("SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1 FROM DUAL",[[]])
```
fails with KeyError: 'parameterData' at
https://github.com/exasol/websocket-api/blob/fedc030b166ed39b56422712d1130ba191177e19/python/EXASOL/__init__.py#L133

**Comment by lynxrv21** [comment]
I got the same error
Is anyone still maintaining this repository to merge mentioned PR?
