### ISSUE TITLE
Python websockets-api is much slower than using ODBC

### ISSUE THREAD

**Issue by datapythonista** [EXASOL/websocket-api#2]
I did some benchmark on getting information from Exasol 6 using this websocket-api, and also pyodbc and turbodbc.

I run 100 queries with each, that fetch 100,000 rows (from a table with one column of the main types (int, float, string and date). The queries are performed using Python 3.6 from the same data center as Exasol, so network shouldn't be the bottleneck.

For the websockets-api we've enabled compression.

The results are shown in this plot:

![exasol_clients_mlan](https://user-images.githubusercontent.com/10058240/29116748-ca829712-7cf3-11e7-942d-2c8dcaef0f75.png)

Is that expected? Or can this client (or the server side of Exasol) be optimized?

**Comment by exaSR** [comment]
Exasol optimized the server side of websockets in Version 6.0.5; could you re-run your tests?

**Comment by exazg** [comment]
There have been a few optimizations (starting with 6.0.5 as mentioned above) on the Exasol/server side of the WebSocket connections. Please try running the tests again using a more recent Exasol version.
