### ISSUE TITLE
7.0rc1: Transaction collision: automatic transaction rollback 

### ISSUE THREAD

**Issue by abergmeier** [exasol/websocket-api#20]
When I open two parallel websocket connections and on both do DROP/CREATE of distinct CONNECTIONS, I get Transaction collisions:

```
# Execute in first Connection:
DROP CONNECTION WS1
CREATE CONNECTION WS1 TO 'FOO'

# Execute in second Connection:
DROP CONNECTION WS2
CREATE CONNECTION WS2 TO 'BAR'
```
Is this to be expected?

For Tables this doesn't seem to be a problem though.
Do global objects need to be handled in one connection only?
Are no parallel mutating transactions on global allowed?

**Comment by exazg** [comment]
Thanks for your questions, but since they are related to transactions as opposed to WebSockets, please contact Exasol customer support regarding this issue. They will be able to better assist you. Thanks!
