### ISSUE TITLE
How to implement paging properly with Websocket API

### ISSUE THREAD

**Issue by vadimtsushko** [exasol/websocket-api#22]
I am currently trying to implement the MVP of a WebSocket API client with Dart. I've got the most basic features up and running relatively quickly. I can connect with successful authentication, run commands `execute` and `fetch` and get results properly.
The next step for me is to implement paging for larger result sets.
I know what data frame I'm querying for the specific page in the front-end application, say rows 300-399 for the third page.
In the `fetch` command, we have the `startPosition` parameter as an analog to SQL `OFFSET` clause. But as far as I can see, there is no parameter corresponding to SQL `LIMIT` clause.

What should I use in WebSocket API to get something like `LIMIT 100 OFFSET 200` ?

**Comment by vadimtsushko** [comment]
Sorry for stupid question, guys.
I somehow assumed that `fetch` feature is necessary for implementing paging, but obviously I can just use LIMIT/OFFSET clause in my SQL statements for that purpose.
I guess that `fetch` feature was designed for streaming big datasets as series of json-data chunks.

I

**Comment by peterkioko** [comment]
Correct, the `startPosition` + `numBytes` parameters are for limiting the size of JSON chunks for client memory-management purposes. For query resultset pagination you would use `LIMIT + OFFSET`, as you said.
