### ISSUE TITLE
HTTP Transport IMPORT quirks

### ISSUE THREAD

**Issue by bobozaur** [exasol/websocket-api#33]
Hello everyone,

I apologize if this isn't the right place to open such an issue, but it's the only place I can find to get in contact with you about these things. I hope that's okay!

I'm the author of https://github.com/bobozaur/sqlx-exasol, a third party driver for the Rust `sqlx` framework for Exasol. The driver uses the websocket API in this repository with the exception of HTTP transport which is implemented based on the `py-exasol` implementation.

I however noticed a few quirks when implementing `IMPORT` and I was wondering if you could help with that in any way. Similarly to how `py-exasol` does things, my driver creates a one-shot HTTP server for each database node and pipes data through them as `chunked-tranfer` encoding.

However, when running an `IMPORT` query, if there's no data getting sent through one of the HTTP responses, Exasol sends a new HTTP request, which basically means it's retrying. 

I documented this behaviour so consumers would know that if they open connections to 5 nodes but only send data to 3 of them and two will starve, the query will return an error because the driver closes the HTTP connection after sending the response (empty, in this case) and when Exasol retries it won't be able to connect.

I've been wondering since then whether there's a limit to that retrying, but I tested and there doesn't seem to be one. Exasol will keep retrying. So I was wondering if there's any way to tell Exasol "Hey, I know I eagerly opened up this TCP connection but I realized I don't have that much data so I sent an empty response to your HTTP request, please don't retry". Maybe a certain HTTP status code or some header?

Another somewhat related quirk is that when using TLS Exasol will send handshakes and HTTP requests for each node sequentially, as opposed to sending all of them concurrently when not using encryption. This gets handled in the code but I can't help but wonder whether this is the expected behavior or not.

Any help would be appreciated!

**Comment by redcatbear** [comment]
Hi @bobozaur. First of all thanks to reaching out to Exasol and to writing a driver for Rust. I contacted the driver team. The maintainers of this API are on vacation at the moment. I wrote them a message to take a look at this ticket when they return.

**Comment by bobozaur** [comment]
Hey @redcatbear ! Thanks a lot for contacting the appropriate team. Looking forward to further discussing about this.

**Comment by redcatbear** [comment]
Hi @bobozaur, the subject matter expert should be back tomorrow. We haven't forgotten you.

**Comment by exazg** [comment]
Hi @bobozaur. Thanks for the question. Hopefully we can figure out what the issue is.

> the query will return an error because the driver closes the HTTP connection after sending the response (empty, in this case) and when Exasol retries it won't be able to connect.

Can you please specify exactly what you're sending as a reply? The HTTP headers and data (if any).

If Exasol had gotten an expected (successful or unsuccessful) reply, I wouldn't have expected it to retry. Are you sure that the response is really being sent?

If there's no data available for an `IMPORT` statement, then I think a 200 response code with no data would be expected and work correctly in this case. Exasol receives a successful response from the server, and no data is actually imported.

**Comment by redcatbear** [comment]
@bobozaur, did you check @exazg's answer to your question?

**Comment by bobozaur** [comment]
Hey guys, sorry for the late reply. Life's been quite hectic lately.

> Can you please specify exactly what you're sending as a reply? The HTTP headers and data (if any).

A 200 chunked encoding response and an empty chunk as a body. A rough example would be:
```http
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked

0\r\n
\r\n
```

> If Exasol had gotten an expected (successful or unsuccessful) reply, I wouldn't have expected it to retry. Are you sure that the response is really being sent?

Absolutely. The problem mainly occurs when there are multiple nodes involved. If only one node is used this seems to be handled gracefully even when no data is sent, but when more nodes are used then what seems to happen is that Exasol connects to them sequentially after each of them provides some data. If one of them does not provide any data, Exasol keeps retrying the HTTP request.

Not only that, but I did test whether there's a limited amount of retries and it's not. Exasol just keeps retrying forever.

> If there's no data available for an `IMPORT` statement, then I think a 200 response code with no data would be expected and work correctly in this case. Exasol receives a successful response from the server, and no data is actually imported.

Please note that this is not exactly what I'm claiming. The issue happens when there _is_ data for the statement, just that it is not distributed throughout all connections used in the `IMPORT` statement. If some connections starve and get no data, an empty chunked response is sent and then the connection is closed. But Exasol will retry the HTTP request in these cases for these starved connections. It will not retry the connection if at least one row of data has been sent through a connection or if only one connection is used and no data is being sent.

I honestly have not tried with just a 200 HTTP status code response _without_ the `Transfer-Encoding` header and a completely empty body. The thing is that it would be a bit painful to implement and I'd rather be a bit more certain that it would solve it before going to the extent of implementing this. I don't think the proper empty chunk response for the `Transfer-Encoding: chunked` header should cause these issues though, as it _is_ handled correctly when only using one node.

I think this whole thing has to do with this sequentiality of the connections. This seems to be the behavior in TLS contexts (handshakes being done sequentially) as well as actual data transfers. I also want to point out that this behavior can be seen in `pyexasol` as well, with the difference that `pyexasol` is synchronous while `sqlx-exasol` is async. What I mean by this is that there is a bit more concurrency in `sqlx-exasol` which tends to make these things more visible.

**Comment by exazg** [comment]
Hi @bobozaur. Thanks for the additional information. I think I understand what the problem is now.

Previously, I thought we were dealing with a retry on a single connection (e.g. a response was not received), but we are really dealing with two different connections. And, as you have already pointed out, the issue arises because some of the connections do not send any data.

Background:
The IMPORT statement in this case is designed to work with files, and when Exasol imports files, it always checks the beginning of the data to see if it has the correct format, etc. Then, it will download and import all of the data.

Problem:
The problem arises if the server does not send any data for a file when Exasol tries to verify it. In this case, Exasol is in the following state: it is time to import data from a file, but Exasol does not have any data for this file from the verification step. So Exasol tries to download the file again.

Possible solutions:
One solution is to avoid starting an HTTPS server on a node without data. This may not be easy as you have mentioned before.

Another solution could be supporting multiple requests for a file. Providing the same response without data (as above) will work. I don't know if this would be feasible or not.

Anyway, I hope this helps. I think the problem is clear now. Hopefully, you can find a good solution. Let us know if/when you get it working or have any further questions.

**Comment by bobozaur** [comment]
@exazg Thanks for looking into this!

The first solution you proposed is what I documented in the driver so consumers would know or at least be aware that they should not start more connections than necessary. I was just wondering if there was some way for me to handle that internally for the sake of making the library more robust.

The second solution is something I have already tried, actually. For testing purposes I tweaked the HTTP server code to instead keep the server alive for an unlimited number of requests in case Exasol retries, hoping that it would retry a limited number of times and eventually stop. However, it keeps retrying indefinitely, even if an empty response like the one above is sent every time (for this particular file/connection; note that others do send data).

Do you perhaps have any idea of something else I could try?

**Comment by redcatbear** [comment]
Great analysis, @exazg. Thank you very much.

**Comment by exazg** [comment]
>it keeps retrying indefinitely
What is the highest number of retries that you have seen for a single file?

While I was looking at this yesterday, the maximum number of requests that I saw for a file was three. Most of the time only two requests should be sent, however.

Perhaps my tests were too short, but I wouldn't expect an indefinite number of retires. Although, I have not verified this.

**Comment by bobozaur** [comment]
Ah, that's great then. Is it possible that the difference in your test is that you're not sending a chunked-encoded response when the file is empty? As in, not passing the `0\r\n\r\n` and the associates HTTP header?

**Comment by exazg** [comment]
No, the server for the empty file uses chunking. I wanted to make sure that this does not cause issues. The other server does not use chunking.

`test_empty.py`
```
self.send_response(200)
self.send_header('transfer-encoding', 'chunked')
self.send_header('Content-Type', 'text/plain')
self.send_header('Connection', 'close')
self.end_headers()

close_chunk = '0\r\n\r\n'
self.wfile.write(close_chunk.encode(encoding='utf-8'))
```

```
$ curl -v http://localhost:8000/test_empty.csv
* About to connect() to localhost port 8000 (#0)
*   Trying ::1...
* Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /test_empty.csv HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8000
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: BaseHTTP/0.6 Python/3.6.8
< Date: Wed, 05 Jun 2024 10:26:15 GMT
< transfer-encoding: chunked
< Content-Type: text/plain
< Connection: close
< 
* Closing connection 0
```

**Comment by bobozaur** [comment]
@exazg Thanks for looking into this so thoroughly. I'll have to do some tests myself and get back to you on this.

**Comment by exazg** [comment]
> When getting a response with an empty file, I think Exasol instead tries to connect to http://10.10.10.11:41741/import_00000.csv again, but that port is busy with the TCP socket used for the HTTP server.

Yes, that is exactly what happens on the Exasol side. Exasol will create a *new* connection for the second (or maybe third) HTTP request.

> What puzzles me is why would Exasol not reuse the same socket connection

There is no reason the keep the connection open. Exasol downloaded the (empty) file. The request is complete.

> Any ideas on where to go from here?

I think all you need to do is allow your HTTP servers to somehow handle more than one connection. I don't know how feasible that is on your side, but that should fix the problem.

**Comment by bobozaur** [comment]
@exazg It's not as simple as having the HTTP server accept multiple requests.

Let's assume that we generally connect to the database at the address `10.10.10.11:8563`.

In the general case you have an HTTP server listening on a certain port, say `10.10.10.10:8000`. So you write your `IMPORT` query accordingly: `IMPORT INTO MY TABLE FROM CSV AT 'http://10.10.10.10:8000' FILE 'my_file.csv'`. 

Exasol will always send the request to `10.10.10.10:8000`, in which case the TCP listener assigns a port on the server and you thus end up with a socket which is uniquely identifiable on a system by a combination of its source and destination addresses. So you can end up with a socket with details such as  `source: 10.10.10.11:12345; destination: 10.10.10.10:8000`. 

If that request serves an empty file and Exasol retries by setting up a different socket connection only the source port will change, so you might end up with something like `source: 10.10.10.11:23456; destination: 10.10.10.10:8000`.

In the driver's case things go slightly different. 

First, a TCP socket gets connected from the _driver side_ to the database (note that in the general case it is the database that initiates the connection). This socket can look like `source: 10.10.10.10:12345; destination: 10.10.10.11:8563`. Note that the socket **always** connects to Exasol's exposed port. Then, the 12 bytes packet in my previous reply gets sent through that socket and an IP and port get received. This always seems to be the Exasol node's IP address and some random port. These will look something like `10.10.10.11:41741`. It thus seems to me that Exasol sets up some sort of internal proxy. So then the `IMPORT` query looks like `IMPORT INTO MY TABLE FROM CSV AT 'http://10.10.10.11:41741' FILE 'my_file.csv'`.

So Exasol will initiate the request towards `10.10.10.11:41741`. But I am 100% positive there's no HTTP server from the driver's side listening to that, not to mention that it's not the client's IP but rather the Exasol node's IP. Which is where I got the theory of the internal proxy.

Exasol will internally route the traffic from `10.10.10.11:41741` to the socket the _driver_ opened, identifiable by `source: 10.10.10.10:12345; destination: 10.10.10.11:8563`. But when the request ends and the response is received, I now believe that the internal proxy itself gets closed. Even if some new socket from the database's side gets opened, it will most likely not be assigned the same `41741` port. So retrying to that address will just keep on failing.

Since the query is still executing there's most likely no way to tell Exasol "hey, route the next request to 10.10.10.11:**new-port**` instead of `10.10.10.11.41741`. So then the question remains on how to keep the internal proxy alive for more HTTP request. Is this what's really happening, though? I might be greatly off track here.

**Comment by exazg** [comment]
> Is this what's really happening, though? I might be greatly off track here.

Yes, that's exactly what happens. I actually forgot about the whole proxy thing and was just focusing on the IMPORT statements.

So, as you mentioned, the "accepting multiple connections for an empty file" won't work. As far as I can tell, that just leaves the option of avoiding empty files altogether. Unfortunately, I can't think of any kind of workaround for that at the moment.

**Comment by bobozaur** [comment]
Is there really nothing else that can be configured regarding the proxy? Maybe setting some sort of keep alive or selecting a specific port so that it matches the one in the IMPORT statement?

**Comment by exazg** [comment]
No, unfortunately, nothing else can be configured with the proxy.

To be honest, this functionality was never intended to be used by non-Exasol drivers/tools. That's why it is not documented in any way. The developer of PyEXASOL discovered and used this functionality completely on his own. And while there's nothing wrong with using it, it's also not a supported interface so to speak. It's more like: You can use it if you want, but we don't support it.

Having said that, I hope you can get this working somehow, and I will help if I can, but I don't currently see any other workarounds/configurations to get this working. The Exasol side of things just wasn't designed for this use case.

**Comment by bobozaur** [comment]
I see. In this case I will close this issue.

Thank you again for all the time put into this! Although the outcome is not necessarily the one I hoped for, I still highly appreciate your efforts. Should the situation change or any idea come to your mind, feel free to open an issue on the Rust driver repository.

Cheers!
