### ISSUE TITLE
Request for Exasol-style IP ranges for websocket connections

### ISSUE THREAD

**Issue by exaSR** [exasol/websocket-api#5]
I noticed that the python EXASOL package seems to be limited to a single host/port combination when connecting to a database.

To sync this with all our other drivers, it would be nice if `EXASOL.connect` would accept a host range like
`ws://192.172.11.11..16:8563`.

**Comment by rrusinov** [comment]
The EXASOL package supplied is merely a sample and is not designed for direct application in a production environment. It should serve as a foundation for developing your own websocket driver. For a ready-to-use Python websocket-based driver, we suggest exploring the pyexasol package: https://github.com/exasol/pyexasol
